[PCH] In ASTReader::FinishedDeserializing, after we do PassInterestingDeclsToConsumer we may end up having added more pending stuff to do, so go in a loop until everything is cleared out.
This fixes the error in rdar://10278815 which has a certain David Lynch-esque quality..

  error: unknown type name 'BOOL'; did you mean 'BOOL'?